DEFINE VARIABLE answer AS LOGICAL NO-UNDO.

MESSAGE "ALERT-BOX 1"
    VIEW-AS ALERT-BOX MESSAGE.

MESSAGE "ALERT-BOX 2"
    VIEW-AS ALERT-BOX MESSAGE TITLE "Custom Title".

MESSAGE "ALERT-BOX QUESTION 1"
    VIEW-AS ALERT-BOX QUESTION BUTTONS YES-NO SET answer.

RUN showAnswer(INPUT answer).

MESSAGE "ALERT-BOX QUESTION 2"
    VIEW-AS ALERT-BOX QUESTION BUTTONS YES-NO SET answer.

RUN showAnswer(INPUT answer).

MESSAGE "ALERT-BOX QUESTION 3"
    VIEW-AS ALERT-BOX QUESTION BUTTONS YES-NO-CANCEL SET answer.

RUN showAnswer(INPUT answer).

MESSAGE "ALERT-BOX INFORMATION"
    VIEW-AS ALERT-BOX INFORMATION.

MESSAGE "ALERT-BOX 4"
    VIEW-AS ALERT-BOX ERROR BUTTONS OK-CANCEL.

RUN showAnswer(INPUT answer).

MESSAGE "ALERT-BOX 5"
    VIEW-AS ALERT-BOX WARNING BUTTONS RETRY-CANCEL.

RUN showAnswer(INPUT answer).

PROCEDURE showAnswer PRIVATE:
    DEFINE INPUT PARAMETER answer AS CHARACTER NO-UNDO.

    IF  answer = ? THEN
        answer = "cancel/retry".

    MESSAGE "Answer is:" STRING(answer)
        VIEW-AS ALERT-BOX INFORMATION BUTTONS OK TITLE CAPS(answer).
END PROCEDURE.

